import type { LucideIcon } from "lucide-react";
import {
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  CircleHelp,
  Clapperboard,
  Coffee,
  CreditCard,
  Droplets,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  Landmark,
  Laptop,
  Library,
  ParkingCircle,
  PawPrint,
  Phone,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shield,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Sparkles,
  Tag,
  Tv,
  Utensils,
  Wallet,
  WashingMachine,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

/** Exact category name → Lucide icon (YNGSB + Income). */
const BY_NAME: Record<string, LucideIcon> = {
  Paycheck: Banknote,
  "Other income": Wallet,

  "Rent/Mortgage": Home,
  Phone: Phone,
  Internet: Wifi,
  "Cable TV": Tv,
  Electricity: Zap,
  Water: Droplets,
  Hidroelectrica: Zap,
  Streaming: Tv,
  "Bani buni": Heart,
  Transport: Bus,
  Software: Laptop,
  EON: Zap,
  Asociatie: Building2,
  Bona: Baby,
  "RCS/RDS": Wifi,
  "Kindergarden&School": GraduationCap,
  Impozite: Landmark,
  Asigurari: Shield,
  "Health Insurance": HeartPulse,

  Groceries: ShoppingCart,
  Fuel: Fuel,
  Medical: HeartPulse,
  Clothing: Shirt,
  "Household Goods": ShoppingBasket,
  Pets: PawPrint,
  Tools: Wrench,
  "Pocket Money Tinel": Wallet,
  "Pocket Money Monica": Briefcase,
  Atelier: Hammer,
  Transactions: Repeat,
  Education: GraduationCap,
  Parcare: ParkingCircle,
  Restaurante: Utensils,
  "Round-up": PiggyBank,
  "Office food": Coffee,
  Library: Library,
  Unknown: CircleHelp,
  Washing: WashingMachine,
  Taxi: Car,
  Presents: Gift,
  Hotels: Hotel,
  "Curatenie & Ironing": Sparkles,
  "Look&Feel": Scissors,
  Carti: BookOpen,
  Toys: Gift,
  Cinema: Clapperboard,
  "Google Play": Laptop,
  Games: Gamepad2,
  "Site-uri": Globe,
  Retragere: Banknote,

  "Emergency Fund": Shield,
  "Car Repairs": Wrench,
  "Home Maintanance": Hammer,
  "Car Insurance": Car,
  "Life Insurance": Heart,
  Birthdays: Cake,
  Christmas: Gift,

  "Car Replacement": Car,
  "Car replacement": Car,
  Vacation: Plane,
  Domains: Globe,

  "Car Payment": Car,
  "Personal Loan Payment": CreditCard,
};

const GROUP_FALLBACK: Record<string, LucideIcon> = {
  Income: Banknote,
  "Monthly Bills": Receipt,
  "Everyday Expenses": ShoppingCart,
  "Rainy Day Funds": Shield,
  "Savings Goals": PiggyBank,
  Debt: CreditCard,
  "Credit Card Payments": CreditCard,
};

export function categoryIcon(
  categoryName: string,
  groupName?: string,
): LucideIcon {
  return (
    BY_NAME[categoryName] ??
    (groupName ? GROUP_FALLBACK[groupName] : undefined) ??
    Tag
  );
}
