/** Seeded from tinel-c/ing-csv-to-ynab-csv mappingCategory. */
export type DefaultImportRule = { matchText: string; categoryName: string; ignore?: boolean };

export const DEFAULT_IMPORT_RULES: DefaultImportRule[] = [
  { matchText: "Detalii: Christmas", categoryName: "Christmas" },
  { matchText: "Detalii: Birthdays", categoryName: "Birthdays" },
  { matchText: "Detalii: Domains", categoryName: "Domains" },
  { matchText: "Detalii: Car replacement", categoryName: "Car replacement" },
  { matchText: "Detalii: Vacation", categoryName: "Vacation" },
  { matchText: "Detalii: Car Repairs", categoryName: "Car Repairs" },
  { matchText: "Detalii: Home maintanance", categoryName: "Home Maintanance" },
  { matchText: "Detalii: Car Insurance", categoryName: "Car Insurance" },
  { matchText: "Tranzactie Round Up", categoryName: "Round-up" },
  { matchText: "Scoala Primara EuroEd", categoryName: "Kindergarden&School" },
  { matchText: "EON GAZ FURNZARE", categoryName: "EON" },
  { matchText: "WWW.EON.RO/MYLINE", categoryName: "EON" },
  { matchText: "E.ON", categoryName: "EON" },
  { matchText: "AS. DE LOCATARI FRUMOASA II", categoryName: "Asociatie" },
  { matchText: "WWW.ORANGE.RO/YOXO", categoryName: "Phone" },
  { matchText: "myorangefix", categoryName: "Internet" },
  { matchText: "ORANGE ROMANIA", categoryName: "Internet" },
  { matchText: "RO92INGB0000999905926537", categoryName: "Bona" },
  { matchText: "HBO", categoryName: "Streaming" },
  { matchText: "RCS AND RDS SA", categoryName: "RCS/RDS" },
  { matchText: "NETFLIX", categoryName: "Streaming" },
  { matchText: "Amazon Video", categoryName: "Streaming" },
  { matchText: "Google Payment", categoryName: "Google Play" },
  { matchText: "YouTubePremium", categoryName: "Streaming" },
  { matchText: "BANGGOOD", categoryName: "Atelier" },
  { matchText: "ALIEXPRES", categoryName: "Atelier" },
  { matchText: "PAYPAL *PATREONIREL", categoryName: "Games" },
  { matchText: "PAYPAL *KINGUINDIGI", categoryName: "Games" },
  { matchText: "PAYPAL *2CO.COM", categoryName: "Games" },
  { matchText: "PAYPAL *DIGITALRIVE", categoryName: "Games" },
  { matchText: "CARREFOUR", categoryName: "Groceries" },
  { matchText: "MPN LOGISTICS", categoryName: "Groceries" },
  { matchText: "Zig Delivero", categoryName: "Groceries" },
  { matchText: "GILCA MIHAI FITNESS", categoryName: "Groceries" },
  { matchText: "Pantiru Mihai PFA", categoryName: "Groceries" },
  { matchText: "LIDL", categoryName: "Groceries" },
  { matchText: "Lidl Discount", categoryName: "Groceries" },
  { matchText: "PICO MAG DEP", categoryName: "Groceries" },
  { matchText: "CRISNIC MARKET", categoryName: "Groceries" },
  { matchText: "Glovo GLOVO PRIME", categoryName: "Groceries" },
  { matchText: "Auchan", categoryName: "Groceries" },
  { matchText: "Terminal: Livrator  RO", categoryName: "Groceries" },
  { matchText: "MARYO S EAST ", categoryName: "Groceries" },
  { matchText: "PENNY ", categoryName: "Groceries" },
  { matchText: "MCS STORE", categoryName: "Groceries" },
  { matchText: "MY EVENTS SRL", categoryName: "Office food" },
  { matchText: "SALAD BOX", categoryName: "Office food" },
  { matchText: "MADO", categoryName: "Office food" },
  { matchText: "OSPATUL ZEILOR", categoryName: "Office food" },
  { matchText: "SIMIGERIA PETRU", categoryName: "Office food" },
  { matchText: "BLACK DOT COFFEE", categoryName: "Office food" },
  { matchText: "NEATA CAFE", categoryName: "Office food" },
  { matchText: "EMAG SHOWR", categoryName: "Household Goods" },
  { matchText: "DM FIL", categoryName: "Household Goods" },
  { matchText: "ALTEX", categoryName: "Household Goods" },
  { matchText: "DM DROGERIE MARKT SRL", categoryName: "Household Goods" },
  { matchText: "MOBILPAY*HAIRCARE", categoryName: "Household Goods" },
  { matchText: "MOL", categoryName: "Fuel" },
  { matchText: "OMV", categoryName: "Fuel" },
  { matchText: "IASI ETAX", categoryName: "Impozite" },
  { matchText: "ING Gold", categoryName: "Impozite" },
  { matchText: "MUNICIPIUL IASI SNEP  RO", categoryName: "Impozite" },
  { matchText: "ETAX", categoryName: "Impozite" },
  { matchText: "ARCADIA", categoryName: "Medical" },
  { matchText: "ARTIMA", categoryName: "Medical" },
  { matchText: "HELP NET FARMA", categoryName: "Medical" },
  { matchText: "SMILE DENT SRL", categoryName: "Medical" },
  { matchText: "FITERMAN", categoryName: "Medical" },
  { matchText: "SENSIBLU", categoryName: "Medical" },
  { matchText: "D.D.I. RADIOLOGIE", categoryName: "Medical" },
  { matchText: "FARMACIA FLORA", categoryName: "Medical" },
  { matchText: "FARMACIA DONA", categoryName: "Medical" },
  { matchText: "ASKLEPIOS-RO", categoryName: "Medical" },
  { matchText: "ROPHARMA", categoryName: "Medical" },
  { matchText: "LARA FARM", categoryName: "Medical" },
  { matchText: "ANA PHARM", categoryName: "Medical" },
  { matchText: "MARELBO", categoryName: "Clothing" },
  { matchText: "KOTON", categoryName: "Clothing" },
  { matchText: "TAKKO", categoryName: "Clothing" },
  { matchText: "ZARA", categoryName: "Clothing" },
  { matchText: "H&M", categoryName: "Clothing" },
  { matchText: "INA IULIUS MALL", categoryName: "Clothing" },
  { matchText: "SIA SOF", categoryName: "Clothing" },
  { matchText: "CCC PALAS", categoryName: "Clothing" },
  { matchText: "MELI MELO FASHION", categoryName: "Clothing" },
  { matchText: "ELEGANT PRICOP", categoryName: "Clothing" },
  { matchText: "ART TRADITIE", categoryName: "Clothing" },
  { matchText: "SOPORAN RAVECA", categoryName: "Clothing" },
  { matchText: "ROUMASPORT", categoryName: "Clothing" },
  { matchText: "HM Hennes", categoryName: "Clothing" },
  { matchText: "Zara.com", categoryName: "Clothing" },
  { matchText: "SAMEDAY.RO", categoryName: "Clothing" },
  { matchText: "MAXI PET IASI ", categoryName: "Pets" },
  { matchText: "MPVET IASI", categoryName: "Pets" },
  { matchText: "SEDCOMLIBRIS", categoryName: "Library" },
  { matchText: "PASTICCERIA MONTECAT", categoryName: "Restaurante" },
  { matchText: "PREMIER RESTAURANTS", categoryName: "Restaurante" },
  { matchText: "MOO CAFE PALAS DEP", categoryName: "Restaurante" },
  { matchText: "MAMMA MIA", categoryName: "Restaurante" },
  { matchText: "TUFFLI DEP RO", categoryName: "Restaurante" },
  { matchText: "KFC", categoryName: "Restaurante" },
  { matchText: "VENETO RESTAURANT SRL", categoryName: "Restaurante" },
  { matchText: "VO CHEF SRL", categoryName: "Restaurante" },
  { matchText: "EVERTOGETHER SRL", categoryName: "Restaurante" },
  { matchText: "N BEES", categoryName: "Restaurante" },
  { matchText: "PASTRY CASA DULCE", categoryName: "Restaurante" },
  { matchText: "NOODLE PACK", categoryName: "Restaurante" },
  { matchText: "CASA TRADITIEI", categoryName: "Restaurante" },
  { matchText: "FRATELLI RISTORANTE", categoryName: "Restaurante" },
  { matchText: "BRIO GROUP", categoryName: "Restaurante" },
  { matchText: "GRAPIC ARTISAN BAKERY", categoryName: "Restaurante" },
  { matchText: "COLUMBUS OPERATIONAL", categoryName: "Restaurante" },
  { matchText: "YOYOUGURT", categoryName: "Restaurante" },
  { matchText: "BETTY ICE", categoryName: "Restaurante" },
  { matchText: "CORSINI PASTICCERI", categoryName: "Restaurante" },
  { matchText: "STRONGMNDCORP.SR", categoryName: "Restaurante" },
  { matchText: "DONUTERIE", categoryName: "Restaurante" },
  { matchText: "BIO BOX SRL", categoryName: "Restaurante" },
  { matchText: "Dinah  Aliment", categoryName: "Restaurante" },
  { matchText: "Veranda  RO", categoryName: "Restaurante" },
  { matchText: "ABI CONCEPT SAPTE", categoryName: "Restaurante" },
  { matchText: "CARTOFISSERIE", categoryName: "Restaurante" },
  { matchText: "SMART BUSINESS", categoryName: "Restaurante" },
  { matchText: "Glovo", categoryName: "Groceries" },
  { matchText: "Iasi 6 Bucium", categoryName: "Unknown" },
  { matchText: "DISTRIBUTION SERVICES", categoryName: "Unknown" },
  { matchText: "COSTACHE M. IONUT", categoryName: "Unknown" },
  { matchText: "Beneficiar:De Basm", categoryName: "Education" },
  { matchText: "EUROSERVICE TECHNOLOGY", categoryName: "Washing" },
  { matchText: "UBER", categoryName: "Taxi" },
  { matchText: "Unorthodox Roa", categoryName: "Presents" },
  { matchText: "AMZNMktplace  GB", categoryName: "Presents" },
  { matchText: "DON SERAFIM", categoryName: "Presents" },
  { matchText: "EP*bilet.ro", categoryName: "Presents" },
  { matchText: "PAYU*IABILET", categoryName: "Presents" },
  { matchText: "GOPAY  *BAVIXO.RO", categoryName: "Presents" },
  { matchText: "Super Entertaining SRL", categoryName: "Presents" },
  { matchText: "EASYBOX STEFAN", categoryName: "Presents" },
  { matchText: "BOAVISTA SPORT HOTEL", categoryName: "Hotels" },
  { matchText: "PRITAX INVEST", categoryName: "Hotels" },
  { matchText: "LAVA&CUCE", categoryName: "Curatenie & Ironing" },
  { matchText: "IULIUS MANAGEMENT CENTER", categoryName: "Parcare" },
  { matchText: "IULIUS PALAS7A ENT", categoryName: "Parcare" },
  { matchText: "ATTRIUS DEVELOPMENTS", categoryName: "Parcare" },
  { matchText: "BLISS BEAUTY", categoryName: "Look&Feel" },
  { matchText: "PROZ.COM", categoryName: "Carti" },
  { matchText: "MOBILPAY*EDITURA-ART", categoryName: "Carti" },
  { matchText: "Kindle Svcs", categoryName: "Carti" },
  { matchText: "NORIEL TOYS", categoryName: "Toys" },
  { matchText: "CINEMA CITY", categoryName: "Cinema" },
  { matchText: "LEROY MERLIN ROMANIA SRL", categoryName: "Home Maintanance" },
  { matchText: "KITCHEN SHOP", categoryName: "Home Maintanance" },
  { matchText: "DEDEMAN", categoryName: "Home Maintanance" },
  { matchText: "ARABESQUE", categoryName: "Home Maintanance" },
  { matchText: "PAYU*EMAG.RO", categoryName: "Home Maintanance" },
  { matchText: "Support Auto", categoryName: "Car Repairs" },
  { matchText: "GLOBEHOSTIN", categoryName: "Site-uri" },
  { matchText: "Retragere numerar", categoryName: "Retragere" },
  { matchText: "Allianz-Tiriac", categoryName: "Asigurari" },
  { matchText: "ALENTEJO", categoryName: "Pocket Money Monica" },
  { matchText: " asigurare de viata", categoryName: "Health Insurance" },
  { matchText: "WALLET", categoryName: "Software" },
  { matchText: "Scribd", categoryName: "Software" },
  { matchText: "Realimentare Extra", categoryName: "", ignore: true },
  { matchText: "transferata din linia de credit", categoryName: "", ignore: true },
  { matchText: "Detalii tranzactie", categoryName: "", ignore: true },
  { matchText: ".", categoryName: "" },
  { matchText: ",", categoryName: "." },
];
