;這是SSCOM的設置保存文件,您在程式中設置好的串口參數和字串資料都會自動保存,請最好不要用外部編輯器改動本文件!  
;如果文件被修改後程式不能打開,請刪除本文件,程式將會自動生成一個新的ini文件.
;靠行首的半形分號是注釋符號
;每行都以回車結束

;當前串口號Port
N80=,COM1
;波特率Band rate
N81=,9600
;數據位Data bits
N82=,8
;停止位Stop bits
N83=,1
;校驗位Parity
;N84=,無法保存,請打開軟體後重新設置
;流控Flow control
;N85=,無法保存,請打開軟體後重新設置

;"="後面的H表示這是個HEX資料串
;"="後面的A表示這是個ASC字串  
;Nx表示第幾條定義的字串(1<x<32)  
N1=H,7E 03 35 01 EF
N2=H,7E 04 31 0F 02 EF
N3=H,7E 02 01 EF
N4=H,7E 02 02 EF
N5=H,7E 02 03 EF
N6=H,7E 02 04 EF
N7=H,7E 03 31 0F EF
N8=H,7E 03 33 01 EF
N9=A,
N10=A,
N11=A,
N12=A,
N13=A,
N14=A,
N15=A,
N16=A,
N17=A,
N18=A,
N19=A,
N20=A,
N21=A,
N22=A,
N23=A,
N24=A,
N25=A,
N26=A,
N27=A,
N28=A,
N29=A,
N30=A,
N31=A,
N32=A,

;主面板ASC字串  
N33=,abcdefg
;主面板HEX資料串
N34=,12 FF 00 30
;主面板發送方式(ASC or HEX)
N35=,A
;主面板字串發送間隔時間  
N36=,1000
;主面板字串發送新行  
N37=,N
;多條字串發送間隔時間  
N38=,1000
;end